-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 15:48:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Alcohol_Quirquincho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Alcohol_Quirquincho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Alcohol_Quirquincho` DEFAULT CHARACTER SET utf8 ;
USE `Alcohol_Quirquincho` ;

-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ci` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `hora_entrada` TIME NOT NULL,
  `salario` DECIMAL(10,2) NULL,
  `borrado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ci_UNIQUE` (`ci` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`empleado_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`empleado_ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bono` DECIMAL(10,2) NOT NULL,
  `borrado` TINYINT NOT NULL DEFAULT 0,
  `empleado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_ventas_empleado1_idx` (`empleado_id` ASC) ,
  CONSTRAINT `fk_empleado_ventas_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ci` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` INT NULL,
  `borrado` TINYINT NOT NULL DEFAULT 0,
  `empleado_ventas_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ci_UNIQUE` (`ci` ASC) ,
  INDEX `fk_cliente_empleado_ventas1_idx` (`empleado_ventas_id` ASC) ,
  CONSTRAINT `fk_cliente_empleado_ventas1`
    FOREIGN KEY (`empleado_ventas_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado_ventas` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`empleado_distribucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`empleado_distribucion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  `vehiculo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_distribucion_empleado1_idx` (`empleado_id` ASC) ,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) ,
  CONSTRAINT `fk_empleado_distribucion_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`empleado_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`empleado_almacen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NOT NULL,
  `puesto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empleado_almacen_empleado1_idx` (`empleado_id` ASC) ,
  CONSTRAINT `fk_empleado_almacen_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`almacen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_almacen_id` INT NOT NULL,
  `num_almacen` INT NOT NULL,
  `tipo_almacen` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_almacen_UNIQUE` (`num_almacen` ASC) ,
  INDEX `fk_almacen_empleado_almacen1_idx` (`empleado_almacen_id` ASC) ,
  CONSTRAINT `fk_almacen_empleado_almacen1`
    FOREIGN KEY (`empleado_almacen_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado_almacen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `almacen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_almacen1_idx` (`almacen_id` ASC) ,
  CONSTRAINT `fk_item_almacen1`
    FOREIGN KEY (`almacen_id`)
    REFERENCES `Alcohol_Quirquincho`.`almacen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`orden_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`orden_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empleado_almacen_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  `fecha_orden` DATE NOT NULL,
  `plazo` DATE NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `pago` CHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_compra_empleado_almacen1_idx` (`empleado_almacen_id` ASC) ,
  INDEX `fk_orden_compra_proveedor1_idx` (`proveedor_id` ASC) ,
  CONSTRAINT `fk_orden_compra_empleado_almacen1`
    FOREIGN KEY (`empleado_almacen_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado_almacen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_compra_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `Alcohol_Quirquincho`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`orden_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`orden_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `orden_compra_id` INT NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_U` DECIMAL(10,2) NOT NULL,
  `fecha_caducidad` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_item_item1_idx` (`item_id` ASC) ,
  INDEX `fk_orden_item_orden_compra1_idx` (`orden_compra_id` ASC) ,
  CONSTRAINT `fk_orden_item_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `Alcohol_Quirquincho`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_item_orden_compra1`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `Alcohol_Quirquincho`.`orden_compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATE NOT NULL,
  `estado_pedido` VARCHAR(10) NOT NULL,
  `tipo_pago` CHAR(8) NOT NULL,
  `empleado_ventas_id` INT NOT NULL,
  `cliente_id` INT NULL,
  `ordencol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_empleado_ventas1_idx` (`empleado_ventas_id` ASC) ,
  INDEX `fk_orden_cliente1_idx` (`cliente_id` ASC) ,
  CONSTRAINT `fk_orden_empleado_ventas1`
    FOREIGN KEY (`empleado_ventas_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado_ventas` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Alcohol_Quirquincho`.`cliente` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `peso` VARCHAR(25) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `almacen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_almacen1_idx` (`almacen_id` ASC) ,
  CONSTRAINT `fk_producto_almacen1`
    FOREIGN KEY (`almacen_id`)
    REFERENCES `Alcohol_Quirquincho`.`almacen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`orden_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`orden_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` DECIMAL(10,2) NOT NULL,
  `cantidad` INT NOT NULL,
  `orden_id` INT NOT NULL,
  `producto_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orden_producto_orden1_idx` (`orden_id` ASC) ,
  INDEX `fk_orden_producto_producto1_idx` (`producto_id` ASC) ,
  CONSTRAINT `fk_orden_producto_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `Alcohol_Quirquincho`.`orden` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_producto_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `Alcohol_Quirquincho`.`producto` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`hoja_carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`hoja_carga` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrega` DATE NOT NULL,
  `orden_id` INT NOT NULL,
  `empleado_distribucion_id` INT NOT NULL,
  `estado_hoja` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hoja_carga_orden1_idx` (`orden_id` ASC) ,
  INDEX `fk_hoja_carga_empleado_distribucion1_idx` (`empleado_distribucion_id` ASC) ,
  CONSTRAINT `fk_hoja_carga_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `Alcohol_Quirquincho`.`orden` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hoja_carga_empleado_distribucion1`
    FOREIGN KEY (`empleado_distribucion_id`)
    REFERENCES `Alcohol_Quirquincho`.`empleado_distribucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `employee_number` VARCHAR(20) NOT NULL,
  `hire_date` DATE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `user_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `password_UNIQUE` (`email` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`confirmar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`confirmar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_confi` TINYINT NOT NULL DEFAULT 1,
  `fecha` DATE NOT NULL,
  `orden_id` INT NOT NULL,
  `activa` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_confirmar_orden1_idx` (`orden_id` ASC) ,
  CONSTRAINT `fk_confirmar_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `Alcohol_Quirquincho`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`hoja_carga_ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`hoja_carga_ordenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hoja_carga_id` INT NOT NULL,
  `orden_id` INT NOT NULL,
  PRIMARY KEY (`id`, `hoja_carga_id`, `orden_id`),
  INDEX `fk_hoja_carga_ordenes_hoja_carga1_idx` (`hoja_carga_id` ASC) ,
  INDEX `fk_hoja_carga_ordenes_orden1_idx` (`orden_id` ASC) ,
  CONSTRAINT `fk_hoja_carga_ordenes_hoja_carga1`
    FOREIGN KEY (`hoja_carga_id`)
    REFERENCES `Alcohol_Quirquincho`.`hoja_carga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hoja_carga_ordenes_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `Alcohol_Quirquincho`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`ordenes_por_hoja_carga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`ordenes_por_hoja_carga` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NOT NULL,
  `activa` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_ordenes_por_hoja_carga_orden1_idx` (`orden_id` ASC) ,
  CONSTRAINT `fk_ordenes_por_hoja_carga_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `Alcohol_Quirquincho`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Alcohol_Quirquincho`.`regist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alcohol_Quirquincho`.`regist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `user` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
